{% set name = "askbot" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/askbot-{{ version }}.tar.gz
  sha256: 60b6f8ee569bea34216868a359fdfbc11ded04a52f08c2fa013142a97a0b0f67

build:
  number: 0
  noarch: python
  entry_points:
    - askbot-setup = askbot.deployment:askbot_setup
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - akismet ==1.0.1
    - beautifulsoup4 <=4.7.1
    - celery >=4.0,<5.0
    - django >=1.11,<3.0
    - django-appconf ==1.0.3
    - django-avatar >=4.0
    - django-countries >=3.3
    - django-followit ==0.4.1
    - django-jinja >=2.0
    - django-keyedcache3 >=1.5.1
    - django-livesettings3 ==1.4.20
    - django-picklefield >=1.0.0
    - django-recaptcha >=1.0.3,<=1.3.0
    - django-robots >=3.1
    - django-tinymce >=2.8.0
    - django_compressor >=2.0,<=2.4
    - html5lib ==0.9999999
    - jinja2 >=2.10
    - jsonfield >=2.0.0
    - markdown2 <=2.3.9
    - mock ==3.0.5
    - oauth2 <=1.9.0.post1
    - pyjwt <=1.7.1
    - python
    - python-cas >=1.4.0,<1.6
    - python-openid2 >=3.0
    - pytz
    - regex
    - requests-oauthlib >=1.2.0
    - requirements-parser >=0.2.0
    - responses >=0.9.0
    - unidecode

test:
  imports:
    - askbot
    - askbot.bin
  commands:
    - pip check
    - askbot-setup --help
  requires:
    - pip

about:
  home: http://askbot.org
  summary: Question and Answer forum, like StackOverflow, written in python and Django
  doc_url: https://pythonhosted.org/askbot/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
